Modification du makefile

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -52,4 +52,23 @@ re: fclean all
 
 # Command to execute
 r: $(NAME)
-	sudo ./$(NAME)
+	./$(NAME)
+
+install:
+	@if [ "$$(id -u)" -ne 0 ]; then \
+		echo "\e[31mYou must use <sudo make install> to proceed the installation !\e[0m"; \
+		echo "Installation failed."; \
+		exit 1; \
+	else \
+		echo "Installing the graphic library..."; \
+		apt -y install libsfml-dev; \
+		echo "Installing the USB library..."; \
+		apt -y install libboost-all-dev; \
+		echo "Setting udev rule..."; \
+		echo 'SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0666", SYMLINK+="port_ESP8266"' | tee /etc/udev/rules.d/99-usb-access.rules; \
+		udevadm control --reload-rules; \
+		udevadm trigger; \
+		echo "udev rule installed. You can now access the device without sudo via /dev/port_ESP8266."; \
+		echo "\e[32m\nThe game is installed!\e[0m"; \
+		echo "\e[35mWrite <make r> to run the game, have fun !!\e[0m"; \
+	fi
